### ISSUE TITLE
Dont work with 2023.2.5

### ISSUE THREAD

**Issue by Airbrando** [ReneNulschDE/ha-smart-eq-connect#1]
It doesnt work with latest version and befir it show miles instead of KM

**Comment by ReneNulschDE** [comment]
Could you please share some more details? What is not working? Is your HA system configured for KM or Mi?

**Comment by Airbrando** [comment]
Hi Rene,Englisch or German ? I can also write in German. My HomeAssistant is configured i think in KMIt was workung till the update comesVon meinem iPhone 14 Pro Max gesendetAm 20.02.2023 um 10:09 schrieb Rene Nulsch ***@***.***>:﻿
Could you please share some more details? What is not working? Is your HA system configured for KM or Mi?

**Comment by ReneNulschDE** [comment]
Hi, As you like oder wie du willst. Was funktioniert nicht?

**Comment by Airbrando** [comment]
Also ich hatte immer eine Kilometer Anzeige. Dann kam ein Update der integration und danach zeigte er mir an anstatt Km dann mi also milesIch habe dann die komplette integration gelöscht und neu eingebunden. Danach zeigt er mir aber unter den integrationen ein setup fehler an obwohl pin richtig ist. Von meinem iPhone 14 Pro Max gesendetAm 20.02.2023 um 11:54 schrieb Rene Nulsch ***@***.***>:﻿
Hi, As you oder wie du willst. Was funktioniert nicht?

**Comment by Airbrando** [comment]
Kannst du was mit dem screenshot anfangen ?Von meinem iPhone 14 Pro Max gesendetAm 20.02.2023 um 12:09 schrieb Christoph Brandt ***@***.***>:﻿Also ich hatte immer eine Kilometer Anzeige. Dann kam ein Update der integration und danach zeigte er mir an anstatt Km dann mi also milesIch habe dann die komplette integration gelöscht und neu eingebunden. Danach zeigt er mir aber unter den integrationen ein setup fehler an obwohl pin richtig ist. <image0.png>Von meinem iPhone 14 Pro Max gesendetAm 20.02.2023 um 11:54 schrieb Rene Nulsch ***@***.***>:﻿
Hi, As you oder wie du willst. Was funktioniert nicht?

**Comment by ReneNulschDE** [comment]
I have published a version 0.4.1 - this release will fix the Mi/Km bug and has a workaround for the expired SSL certificate on the smart.com website

**Comment by maurizioandreotti60** [comment]
The integration was not working anymore. Even deleting and readding integration. I was at HA release 2023.2.3
After downloading version 0.4.1 I was able to add successfully the integration.
Thanks.

**Comment by Airbrando** [comment]
Geil geht wieder. Vielen lieben Dank ReneVon meinem iPhone 14 Pro Max gesendetAm 21.02.2023 um 17:16 schrieb maurizioandreotti60 ***@***.***>:﻿
The integration was not working anymore. Even deletind and readding integration. I was at HA release 2023.2.3
After downloading version 0.4.1 I was able to add successfully the integration.
Thanks.

**Comment by ReneNulschDE** [comment]
The server certificate on the smart sub website is expired. I disabled the SSL-cert check for now.
